import hashlib
import os
import shutil

# Code generated by PISS (ChatGPT), compiled by reyqune
# Function to calculate the SHA-256 hash of a file
def calculate_sha256(file_path):
    sha256_hash = hashlib.sha256()
    with open(file_path, "rb") as f:
        for byte_block in iter(lambda: f.read(4096), b""):
            sha256_hash.update(byte_block)
    return sha256_hash.hexdigest()

# Function to verify the hash of the file
def verify_file_hash(file_path, expected_hash):
    file_hash = calculate_sha256(file_path)
    if file_hash.lower() != expected_hash.lower():
        raise ValueError(f"File {file_path} hash mismatch! Expected {expected_hash}, but got {file_hash}. "
                         "Please verify the integrity of the files through GoG Galaxy.")
    else:
        print(f"File {file_path} hash verified successfully.")

# Function to create a backup of the file
def backup_file(file_path):
    backup_path = file_path + ".bak"
    if not os.path.exists(backup_path):  # Only create backup if it doesn't already exist
        shutil.copy2(file_path, backup_path)
        print(f"Backup created: {backup_path}")
    else:
        print(f"Backup already exists: {backup_path}")

# Hex editing function
def hex_edit(file_path, original_bytes, new_bytes):
    if len(original_bytes) != len(new_bytes):
        raise ValueError("Original and new byte sequences must be of equal length")
    
    with open(file_path, 'r+b') as f:
        data = f.read()
        offset = data.find(original_bytes)
        
        if offset == -1:
            raise ValueError(f"Original bytes not found in {file_path}")
        
        f.seek(offset)
        f.write(new_bytes)
        print(f"Patched {file_path} at offset {hex(offset)}")

# Hexadecimal byte sequences (as bytes objects)
original_bytes = b'\x5C\x5F\x5E\x5D\x5B\xC3\xCC\xCC\x48\x89\x5C\x24\x18\x48\x89\x6C\x24\x20\x56\x48'
new_bytes = b'\x5C\x5F\x5E\x5D\x5B\xC3\xCC\xCC\xC3\xCC\xCC\xCC\xCC\x48\x89\x6C\x24\x20\x56\x48'

# File paths (replace with the actual paths to your files)
file_bg3 = "bg3.exe"
file_bg3_dx11 = "bg3_dx11.exe"

# Expected SHA-256 hashes for GoG version
expected_hash_bg3_gog = "47FD2193B282827360F146BD5F309C53845A925FB725DCD7B0EE870829BB238C"
expected_hash_bg3_dx11_gog = "26CBFD0EE65C922E615315DE6DBB876BEEAC682F12161F65157BFD920679D779"

# Function to pause and wait for user input before exiting
def pause_and_exit(message):
    print(message)
    input("Press Enter to exit...")  # Wait for user to press Enter before exiting

# Apply the patches for GoG version
try:
    # Verify file hashes before applying patches
    verify_file_hash(file_bg3, expected_hash_bg3_gog)
    verify_file_hash(file_bg3_dx11, expected_hash_bg3_dx11_gog)

    # Backup files before making changes
    backup_file(file_bg3)
    backup_file(file_bg3_dx11)
    
    # Apply the hex edits if the hashes are valid
    hex_edit(file_bg3, original_bytes, new_bytes)
    hex_edit(file_bg3_dx11, original_bytes, new_bytes)
    
    print("Patching complete.")
except Exception as e:
    pause_and_exit(f"Error: {e}")
